model:
  base_learning_rate: 1.0e-06
  target: ldm.models.diffusion.ddpm.LatentDiffusion
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: img
    cond_stage_key: mixed
    image_size: 32
    channels: 4
    cond_stage_trainable: true
    conditioning_key: crossattn
    monitor: val/loss_simple_ema
    unet_config:
      target: ldm.modules.diffusionmodules.openaimodel.UNetModel
      params:
        image_size: 32
        in_channels: 4
        out_channels: 4
        model_channels: 256
        attention_resolutions:
        - 4
        - 2
        - 1
        num_res_blocks: 2
        channel_mult:
        - 1
        - 2
        - 4
        num_head_channels: 32
        use_spatial_transformer: true
        transformer_depth: 1
        context_dim: 512
    first_stage_config:
      target: ldm.models.autoencoder.VQModelInterface
      params:
        embed_dim: 4
        n_embed: 16384
        ckpt_path: models/first_stage_models/vq-f8/model.ckpt
        ddconfig:
          double_z: false
          z_channels: 4
          resolution: 256
          in_channels: 3
          out_ch: 3
          ch: 128
          ch_mult:
          - 1
          - 2
          - 2
          - 4
          num_res_blocks: 2
          attn_resolutions:
          - 32
          dropout: 0.0
        lossconfig:
          target: torch.nn.Identity
    cond_stage_config:
      target: STDiff.models.UnetCond
      params:
        device: cuda:3
        cond_args:
          type: fourier
          dequant: gauss
          noise: 0
          noise_f_int:
          - null
          noise_f:
          - 263.246328125
          - 7.791666666666667
          - 0
          dims: 6
          lr: 1
          lin_lr: 0.01
          f_manual:
          - 1.839835728952772
          - 672
          include_lin: true
data:
  target: main.DataModuleFromConfig
  params:
    batch_size: 32
    num_workers: 0
    wrap: false
    train:
      target: STDiff.dataset_wlbl.ImageNetVidDataset
      params:
        batch_size: 1
        len_seq: 1
        path: /home/nkalanat/sensei-fs-3-link/data/fpe-westbrook/
        path_weather: /home/nkalanat/sensei-fs-3-link/data/
        phase: trainval
    validation:
      target: STDiff.dataset_wlbl.ImageNetVidDataset
      params:
        batch_size: 1
        len_seq: 1
        path: /home/nkalanat/sensei-fs-3-link/data/fpe-westbrook/
        path_weather: /home/nkalanat/sensei-fs-3-link/data/
        phase: test
    test:
      target: STDiff.dataset_wlbl.ImageNetVidDataset
      params:
        batch_size: 1
        len_seq: 1
        path: /home/nkalanat/sensei-fs-3-link/data/fpe-westbrook/
        path_weather: /home/nkalanat/sensei-fs-3-link/data/
        phase: test


lightning:
  callbacks:
    image_logger:
      target: main.ImageLogger
      params:
        batch_frequency: 5000
        max_images: 32
        increase_log_steps: False

  trainer:
    benchmark: True


